CREATE TABLE podcast (
  id INTEGER PRIMARY KEY NOT NULL,
  src TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL
);

CREATE TABLE episode (
  id INTEGER PRIMARY KEY NOT NULL,
  guid TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  src TEXT NOT NULL,
  progress INTEGER NOT NULL,
  duration INTEGER NOT NULL,
  publication INTEGER NOT NULL,
  image TEXT NOT NULL,
  position INTEGER, -- UNIQUE DEFERRABLE INITIALLY DEFERRED,
  podcast INTEGER NOT NULL,
  FOREIGN KEY (podcast) REFERENCES podcast (id)
  );
